### PR TITLE
Add GCP adapter for S3 compatible interfaces and added data mover interfaces for GCP backend

### PR DESCRIPTION
**Pull request by Click2Cloud-Gamma**
New updated PR, this PR adds GCP adapter for S3 compatible interfaces and migration scenario from GCP to AWS also tested.

### CODE REVIEW

**Comment by sfzeng** [comment]
Hi, two suggestions:
1. Migration from other cloud  to GCP also need to be tested.
2. Remove duplicated import record, for example, the following two records are duplicate:
"github.com/webrtcn/s3client"
. "github.com/webrtcn/s3client"

**Comment by Click2Cloud-Gamma** [comment]
Hi,
1. Migration from other cloud to GCP is done.
    
2.  "github.com/webrtcn/s3client" 
    . "github.com/webrtcn/s3client" both import have different significant so it generate errors if removed.
(.) import let  the package's exported identifiers  declared in the current file's file block and can be accessed without a qualifier.so some places it is utilising reference.

**Comment by sfzeng** [comment]
Well, for the second one, maybe you can try to reference each identifier exported from the package in the same way, say, with the prefix of (s3client.) 
But that is not necessary, just a suggestion.

**Comment by Click2Cloud-Gamma** [comment]
@sfzeng it is increasing complexity so if current way is accepted please let us know.

**Comment by sfzeng** [comment]
OK, go ahead please.

**Comment by Click2Cloud-Gamma** [comment]
@sfzeng thanks. we are waiting for your final review and merge update.

**Comment by sfzeng** [comment]
@Click2Cloud-Gamma It's OK, need @xing-yang to merge.

**Comment by wisererik** [comment]
LGTM~

**Pull request merged**
