### PR TITLE
Delete Objects after Migrating all objects

### PR DESCRIPTION
**Pull request by Click2Cloud-Gamma**
In current OpenSDS, when we migrate objects for eg. 10 objects (remain source is false), when each objects gets migrated successfully it gets deleted before migration of other objects.

In case of failure eg. if 3 objects are already migrated, it will get deleted too from source and if migration got failed then we will have 7 objects in source (3 objects got deleted) and 3 objects in destination. 

Using this patch, in same scenario of migration failure, after failure we will have 10 objects in source (No loss of objects from Source bucket) and destination will have 3 objects. So at least at source bucket user will get access to all objects after failure also.

### CODE REVIEW

**Comment by Click2Cloud-Gamma** [comment]
Hi @kumarashit @sfzeng @wisererik. Please review, Thanks

**Comment by wisererik** [comment]
if the 3 objects are very big, it's costly to keep object in source bucket and target bucket.

**Comment by kumarashit** [comment]
IMO, This should be user discretion to either keep it or delete it. There is cost involved here so user can take a call

**Comment by sfzeng** [comment]
Before migration finished, the user needs to pay double the price for those migrated objects. So IMO,  it's better to give the user to make a choice or leave it as it now.

**Comment by Click2Cloud-Gamma** [comment]
> Before migration finished, the user needs to pay double the price for those migrated objects. So IMO, it's better to give the user to make a choice or leave it as it now.

So I think the existing "remainSource" parameter is enough for that, no need to add 1 more parameter.

**Comment by sfzeng** [comment]
> > Before migration finished, the user needs to pay double the price for those migrated objects. So IMO, it's better to give the user to make a choice or leave it as it now.
> 
> So I think the existing "remainSource" parameter is enough for that, no need to add 1 more parameter.

But does this PR is talking about, if user choose to not remain source, then when will we delete the source object?

**Comment by Click2Cloud-Gamma** [comment]
> > > Before migration finished, the user needs to pay double the price for those migrated objects. So IMO, it's better to give the user to make a choice or leave it as it now.
> > 
> > 
> > So I think the existing "remainSource" parameter is enough for that, no need to add 1 more parameter.
> 
> But does this PR is talking about, if user choose to not remain source, then when will we delete the source object?

Using this patch, If `remainSource=false` ,all the objects will get deleted after migrating ALL objects.

**Pull request closed without merging**
