### PR TITLE
list objects with versions

### PR DESCRIPTION
**Pull request by rhsakarpos**
**this PR adds the ability to ListObjects to return all versions of all objects**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
This PR replaces PR #737 
1. Support listing all versions of all objects
2. Instead of returning a list of objects, now returns a list of list of objects

```

### CODE REVIEW

**Comment by sfzeng** [comment]
Hi @rhsakarpos could you please add a comment to explain how dashboard works for list object versions?

**Comment by rhsakarpos** [comment]
Hi @sfzeng sure, this is what we have discussed this morning for dashboard, please let us know your inputs. Tagging @kumarashit and @anvithks and @nguptaopensds
So the dashboard, will now get a 2D-Array (instead of an array  earlier). This will look like below
[o1-v3][o1-v2][o1-v1]
[o2-v2][o2-v1]
if we have 2 objects o1 (with 3 versions) and o2 (with 2 versions). Now, in dashboard, we will highlight the latest version of each object, but list all versions. Also, operations will be allowed only on the latest versions of each object (this will be upgraded post DAITO), like on the [i][0] index of all elements in the 2D array.

**Comment by sfzeng** [comment]
Hi @rhsakarpos thanks for your explanation. And I'm just thinking, is it possible to add a switch to indicate list history version or not? For example, if the switch on, then all list will be list, otherwise only list the current version, and switch is off as default. Cause for some scenario, use may not concern about the history versions.

**Comment by rhsakarpos** [comment]
hi @sfzeng good idea, will do

**Comment by rhsakarpos** [comment]
> Any impact on current feature? Please add test report

@wisererik yes, this will have impact on existing features. Once this PR is merged, then we 

1. can test versioning feature alone from UI (upload, list and download specific version)
2. next, we test related features like migration, life-cycle, copy object etc. spot and fix the issues
This is the plan we have discussed for this feature 
@kumarashit @nguptaopensds please update if i have missed something. Thanks.

**Comment by kumarashit** [comment]
> > Any impact on current feature? Please add test report
> 
> @wisererik yes, this will have impact on existing features. Once this PR is merged, then we
> 
> 1. can test versioning feature alone from UI (upload, list and download specific version)
> 2. next, we test related features like migration, life-cycle, copy object etc. spot and fix the issues
>    This is the plan we have discussed for this feature
>    @kumarashit @nguptaopensds please update if i have missed something. Thanks.

Yes, this is what we discussed as plan

**Comment by anvithks** [comment]
@rhsakarpos Does this PR take care of the response structure being encapsulated in `<Result>` ?

**Comment by skdwriting** [comment]
@rhsakarpos as we discussed yesterday, are we going to support the latest version as a list?

**Comment by sfzeng** [comment]
Hi @rhsakarpos Consider PR#791 together, what the end-user can get by list objects API finally?

**Comment by rhsakarpos** [comment]
closing, since could not merge  > 10 days

**Pull request closed without merging**
